[package]
name = "metrics"
version = "0.1.0"
authors = [""]
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
futures = "0.1.28"
hyper = "0.12.33"
lazy_static = "1.3.0"
prometheus = "0.4.2"
serde_json = "1.0.40"
